# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charles Fayal's Personal Website
email: CharlesFayal@gmail.com
description: > 
  This is my personal website project. I am using this website as a way to learn a number of skills.
  I am hoping to learn more about coding, website development, databases etc.
# this means to ignore newlines until "baseurl:"
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://CharlesFayaal.com" # the base hostname & protocol for your site
twitter_username: chazchuckchip
github_username:  CharlesFayal

# Build settings
markdown: kramdown
